server:
  port: 9528

spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://192.168.4.111:3306/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
#    username: root
#    password: zongyu
#    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: pay_routh1
          uri: http://localhost:9001
          predicates:
            - Path=/pay/**
#    sentinel:
#      transport:
#        dashboard: localhost:8080 # 配置sentinel dashboard控制台服务地址
#        port: 8719 # 默认8719端口，如被占用则自动从8719开始一次+1扫描，直到未被占用