server:
  port: 80

spring:
  application:
    name: cloud-order-service

  # consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: # 显示cloud-payment-service
        prefer-ip-address: true #优先使用服务ip进行注册
        service-name: ${spring.application.name}
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000 # 连接超时时间，打通网络连接
            readTimeout: 3000 #读取超时时间，业务处理
#          cloud-payment-service:
#            connectTimeout: 5000 # 连接超时时间，打通网络连接
#            readTimeout: 5000 #读取超时时间，业务处理

  # springboot项目可以用yml配置，也可在需要的字段上增加注解：@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8