server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  # consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: # 显示cloud-payment-service
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 # 路由的ID类似sql主键ID，没有固定规则
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/** # 断言，路径相匹配的进行路由
#            - name: My
#              args:
#                userType: diamond
            - My=diamond
#            - Query=color,green
#            - RemoteAddr=192.168.4.1/24
#            - Method=GET,POST
#            - Host=**.zongyu.org,**.zongyu.com
#            - Header=X-Request-Id, \d+ # 请求头X-Request-Id且值是正数
#            - Cookie=username,zongyu
#            - Between=2024-05-29T10:15:46.345946500+08:00[Asia/Shanghai], 2024-05-29T10:19:46.345946500+08:00[Asia/Shanghai]  # 在指定日期之间，可访问
#            - Before=2024-05-29T10:15:46.345946500+08:00[Asia/Shanghai] # 在指定日期之前，可访问
#            - After=2024-05-29T11:15:46.345946500+08:00[Asia/Shanghai] # 在指定日期之后，可访问

        - id: pay_routh1
          #          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**