server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  # consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: # 显示cloud-payment-service
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 # 路由的ID类似sql主键ID，没有固定规则
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/** # 断言，路径相匹配的进行路由
#            - name: My
#              args:
#                userType: diamond

#            - My=diamond

#            - Query=color,green
#            - RemoteAddr=192.168.4.1/24
#            - Method=GET,POST
#            - Host=**.zongyu.org,**.zongyu.com
#            - Header=X-Request-Id, \d+ # 请求头X-Request-Id且值是正数
#            - Cookie=username,zongyu
#            - Between=2024-05-29T10:15:46.345946500+08:00[Asia/Shanghai], 2024-05-29T10:19:46.345946500+08:00[Asia/Shanghai]  # 在指定日期之间，可访问
#            - Before=2024-05-29T10:15:46.345946500+08:00[Asia/Shanghai] # 在指定日期之前，可访问
#            - After=2024-05-29T11:15:46.345946500+08:00[Asia/Shanghai] # 在指定日期之后，可访问

        - id: pay_routh2
          uri: lb://cloud-payment-service
          predicates:
#            - Path=/XYZ/abc/{segment}
#            - Path=/pay/gateway/filter/**
            - Path=/gateway/filter/**
          filters:
            - PrefixPath=/pay
#            - RedirectTo=302, http://www.baidu.com
#            - SetPath=/pay/gateway/{segment}
#            - AddRequestHeader=X-Request-zongyu1, zongyuvalue1
#            - AddRequestHeader=X-Request-zongyu2, zongyuvalue2
#            - RemoveRequestHeader=zc
#            - SetRequestHeader=jh, Blue
#            - AddRequestParameter=customerId, 963258
#            - RemoveRequestParameter=customerName
#            - AddResponseHeader=X-Response-Red, Blue
#            - RemoveResponseHeader=Content-Type
#            - SetResponseHeader=Date, 2035-10-01

        - id: pay_routh3
          #          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**